Repository acm-ucr/tsu-website, pull requests merged in 2025-07, with the labels that each got.

#16 Navigation Bar
  src/app/globals.css
  src/app/layout.tsx
  src/components/NavBar.tsx
  src/data/NavBarLinks.ts
Labels: approve x1

#15 Created Footer
  package-lock.json
  package.json
  src/app/layout.tsx
  src/components/Footer.tsx
  src/components/NavBar.tsx
Labels: approve x1

#32 "Who Are We" to Component
  src/app/page.tsx
  src/components/home/whoAreWe.tsx
Labels: ready for review

#33 404 Page
  src/app/globals.css
  src/app/not-found.tsx
Labels: approve x1

#30 Turned "About Us" header into a component
  src/app/about/page.tsx
  src/components/about/header.tsx
Labels: ready for review

#22 "Why Join Us" section
  src/app/page.tsx
  src/components/home/whyJoinUs.tsx
Labels: ready for review

#20 ptag board header
  src/app/board/page.tsx
  src/components/board/header.tsx
Labels: address comments

#47 About Us Photos
  public/polaroid.webp
  public/polaroid2.webp
  src/app/about/page.tsx
  src/components/NavBar.tsx
  src/components/about/header.tsx
  src/components/about/polaroid.tsx
Labels: ready for review
